In [183]:
import pandas as pd

In [184]:
d_jan25_=pd.read_excel("AQI_hourly_city_level_delhi_2025_January_delhi_January_2025.xlsx")
d_feb25_=pd.read_excel("AQI_hourly_city_level_delhi_2025_February_delhi_February_2025.xlsx")
d_mar25=pd.read_excel("AQI_hourly_city_level_delhi_2025_March_delhi_March_2025.xlsx")
d_apr25=pd.read_excel("AQI_hourly_city_level_delhi_2025_April_delhi_April_2025.xlsx")
d_may25=pd.read_excel("AQI_hourly_city_level_delhi_2025_April_delhi_April_2025.xlsx")
d_jun25=pd.read_excel("AQI_hourly_city_level_delhi_2025_June_delhi_June_2025.xlsx")
d_jul25=pd.read_excel("AQI_hourly_city_level_delhi_2025_July_delhi_July_2025.xlsx")
d_aug25=pd.read_excel("AQI_hourly_city_level_delhi_2025_August_delhi_August_2025.xlsx")
d_sep25_=pd.read_excel("AQI_hourly_city_level_delhi_2025_September_delhi_September_2025.xlsx")
d_oct25=pd.read_excel("AQI_hourly_city_level_delhi_2025_October_delhi_October_2025.xlsx")
d_nov25=pd.read_excel("AQI_hourly_city_level_delhi_2025_November_delhi_November_2025.xlsx")
d_dec25=pd.read_excel("AQI_hourly_city_level_delhi_2025_December_delhi_December_2025.xlsx")

In [185]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_dec25 = d_dec25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_dec25["Average"] = d_dec25.iloc[:, 1:].mean(axis=1)
#month number
d_dec25["Month"]=12
#one hot encoding
d_dec25["Delhi"]=1
d_dec25["Gwalior"]=0
d_dec25["Jabalpur"]=0
#dropping columns
d_dec_preprocess = d_dec25.drop(columns=d_dec25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_dec_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0  302.416667     12      1        0         0
1    2.0  353.166667     12      1        0         0
2    3.0  355.625000     12      1        0         0
3    4.0  304.347222     12      1        0         0
4    5.0  325.625000     12      1        0         0
5    6.0  329.750000     12      1        0         0
6    7.0  308.916667     12      1        0         0
7    8.0  313.291667     12      1        0         0
8    9.0  287.083333     12      1        0         0
9   10.0  264.958333     12      1        0         0
10  11.0  293.791667     12      1        0         0
11  12.0  341.333333     12      1        0         0
12  13.0  412.208333     12      1        0         0
13  14.0  461.416667     12      1        0         0
14  15.0  438.875000     12      1        0         0
15  16.0  366.833333     12      1        0         0
16  17.0  330.833333     12      1        0         0
17  18.0  366.583333     12      1        0         0
18  19.0  379.833333     12      1        0         0
19  20.0  389.791667     12      1        0         0
20  21.0  384.250000     12      1        0         0
21  22.0  371.708333     12      1        0         0
22  23.0  407.625000     12      1        0         0
23  24.0  308.500000     12      1        0         0
24  25.0  227.916667     12      1        0         0
25  26.0  313.750000     12      1        0         0
26  27.0  368.625000     12      1        0         0
27  28.0  393.000000     12      1        0         0
28  29.0  402.416667     12      1        0         0
29  30.0  385.375000     12      1        0         0
30  31.0  379.958333     12      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3243076271.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3243076271.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [186]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_jan25_ = d_jan25_.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_jan25_["Average"] = d_jan25_.iloc[:, 1:].mean(axis=1)
#month number
d_jan25_["Month"]=1
#one hot encoding
d_jan25_["Delhi"]=1
d_jan25_["Gwalior"]=0
d_jan25_["Jabalpur"]=0
#dropping columns
d_jan_preprocess_ = d_jan25_.drop(columns=d_jan25_.loc[:, "00:00:00":"23:00:00"].columns)


print(d_jan_preprocess_)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0  326.625000      1      1        0         0
1    2.0  316.750000      1      1        0         0
2    3.0  358.375000      1      1        0         0
3    4.0  381.319444      1      1        0         0
4    5.0  356.625000      1      1        0         0
5    6.0  325.125000      1      1        0         0
6    7.0  304.125000      1      1        0         0
7    8.0  306.791667      1      1        0         0
8    9.0  331.541667      1      1        0         0
9   10.0  400.833333      1      1        0         0
10  11.0  341.458333      1      1        0         0
11  12.0  281.291667      1      1        0         0
12  13.0  263.875000      1      1        0         0
13  14.0  263.166667      1      1        0         0
14  15.0  361.416667      1      1        0         0
15  16.0  328.833333      1      1        0         0
16  17.0  290.708333      1      1        0         0
17  18.0  255.708333      1      1        0         0
18  19.0  342.250000      1      1        0         0
19  20.0  331.875000      1      1        0         0
20  21.0  287.416667      1      1        0         0
21  22.0  261.500000      1      1        0         0
22  23.0  256.916667      1      1        0         0
23  24.0  204.916667      1      1        0         0
24  25.0  183.500000      1      1        0         0
25  26.0  201.083333      1      1        0         0
26  27.0  254.041667      1      1        0         0
27  28.0  269.416667      1      1        0         0
28  29.0  340.458333      1      1        0         0
29  30.0  371.930556      1      1        0         0
30  31.0  351.291667      1      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\553872527.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\553872527.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [187]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_feb25_ = d_feb25_.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_feb25_["Average"] = d_feb25_.iloc[:, 1:].mean(axis=1)
#month number
d_feb25_["Month"]=2
#one hot encoding
d_feb25_["Delhi"]=1
d_feb25_["Gwalior"]=0
d_feb25_["Jabalpur"]=0
#dropping columns
d_feb_preprocess = d_feb25_.drop(columns=d_feb25_.loc[:, "00:00:00":"23:00:00"].columns)


print(d_feb_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0      1  353.291667      2      1        0         0
1      2  333.958333      2      1        0         0
2      3  291.458333      2      1        0         0
3      4  262.708333      2      1        0         0
4      5  290.333333      2      1        0         0
5      6  214.583333      2      1        0         0
6      7  165.250000      2      1        0         0
7      8  149.458333      2      1        0         0
8      9  208.166667      2      1        0         0
9     10  263.583333      2      1        0         0
10    11  284.208333      2      1        0         0
11    12  236.083333      2      1        0         0
12    13  136.666667      2      1        0         0
13    14  130.625000      2      1        0         0
14    15  168.666667      2      1        0         0
15    16  271.083333      2      1        0         0
16    17  242.375000      2      1        0         0
17    18  211.000000      2      1        0         0
18    19  180.833333      2      1        0         0
19    20  162.583333      2      1        0         0
20    21  144.791667      2      1        0         0
21    22  164.583333      2      1        0         0
22    23  137.416667      2      1        0         0
23    24  170.750000      2      1        0         0
24    25  193.375000      2      1        0         0
25    26  231.750000      2      1        0         0
26    27  232.375000      2      1        0         0
27    28  126.916667      2      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\2860051257.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:

In [188]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_mar25 = d_mar25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_mar25["Average"] = d_mar25.iloc[:, 1:].mean(axis=1)
#month number
d_mar25["Month"]=3
#one hot encoding
d_mar25["Delhi"]=1
d_mar25["Gwalior"]=0
d_mar25["Jabalpur"]=0
#dropping columns
d_mar_preprocess = d_mar25.drop(columns=d_mar25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_mar_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0  124.750000      3      1        0         0
1    2.0  126.166667      3      1        0         0
2    3.0  133.666667      3      1        0         0
3    4.0  148.916667      3      1        0         0
4    5.0  116.750000      3      1        0         0
5    6.0  121.500000      3      1        0         0
6    7.0  182.750000      3      1        0         0
7    8.0  164.750000      3      1        0         0
8    9.0  192.458333      3      1        0         0
9   10.0  198.125000      3      1        0         0
10  11.0  240.129630      3      1        0         0
11  12.0  235.833333      3      1        0         0
12  13.0  172.750000      3      1        0         0
13  14.0  192.875000      3      1        0         0
14  15.0  105.875000      3      1        0         0
15  16.0   89.833333      3      1        0         0
16  17.0  102.000000      3      1        0         0
17  18.0  130.666667      3      1        0         0
18  19.0  151.250000      3      1        0         0
19  20.0  156.125000      3      1        0         0
20  21.0  147.333333      3      1        0         0
21  22.0  153.166667      3      1        0         0
22  23.0  175.583333      3      1        0         0
23  24.0  189.263889      3      1        0         0
24  25.0  219.250000      3      1        0         0
25  26.0  233.166667      3      1        0         0
26  27.0  250.500000      3      1        0         0
27  28.0  221.375000      3      1        0         0
28  29.0  157.083333      3      1        0         0
29  30.0  136.250000      3      1        0         0
30  31.0  146.291667      3      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3050156382.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3050156382.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [189]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_apr25 = d_apr25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_apr25["Average"] = d_apr25.iloc[:, 1:].mean(axis=1)
#month number
d_apr25["Month"]=4
#one hot encoding
d_apr25["Delhi"]=1
d_apr25["Gwalior"]=0
d_apr25["Jabalpur"]=0
#dropping columns
d_apr_preprocess = d_apr25.drop(columns=d_apr25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_apr_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0  144.333333      4      1        0         0
1    2.0  202.333333      4      1        0         0
2    3.0  221.041667      4      1        0         0
3    4.0  216.777778      4      1        0         0
4    5.0  172.125000      4      1        0         0
5    6.0  195.541667      4      1        0         0
6    7.0  238.708333      4      1        0         0
7    8.0  233.250000      4      1        0         0
8    9.0  235.833333      4      1        0         0
9   10.0  243.541667      4      1        0         0
10  11.0  173.055556      4      1        0         0
11  12.0  134.916667      4      1        0         0
12  13.0  139.333333      4      1        0         0
13  14.0  175.458333      4      1        0         0
14  15.0  167.708333      4      1        0         0
15  16.0  191.000000      4      1        0         0
16  17.0  194.375000      4      1        0         0
17  18.0  208.750000      4      1        0         0
18  19.0  167.416667      4      1        0         0
19  20.0  144.000000      4      1        0         0
20  21.0  186.833333      4      1        0         0
21  22.0  223.541667      4      1        0         0
22  23.0  219.782407      4      1        0         0
23  24.0  231.152778      4      1        0         0
24  25.0  248.958333      4      1        0         0
25  26.0  252.208333      4      1        0         0
26  27.0  229.708333      4      1        0         0
27  28.0  257.750000      4      1        0         0
28  29.0  225.541667      4      1        0         0
29  30.0  192.000000      4      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1228698317.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1228698317.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [190]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_may25 = d_may25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_may25["Average"] = d_may25.iloc[:, 1:].mean(axis=1)
#month number
d_may25["Month"]=5
#one hot encoding
d_may25["Delhi"]=1
d_may25["Gwalior"]=0
d_may25["Jabalpur"]=0
#dropping columns
d_may_preprocess = d_may25.drop(columns=d_may25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_may_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0  144.333333      5      1        0         0
1    2.0  202.333333      5      1        0         0
2    3.0  221.041667      5      1        0         0
3    4.0  216.777778      5      1        0         0
4    5.0  172.125000      5      1        0         0
5    6.0  195.541667      5      1        0         0
6    7.0  238.708333      5      1        0         0
7    8.0  233.250000      5      1        0         0
8    9.0  235.833333      5      1        0         0
9   10.0  243.541667      5      1        0         0
10  11.0  173.055556      5      1        0         0
11  12.0  134.916667      5      1        0         0
12  13.0  139.333333      5      1        0         0
13  14.0  175.458333      5      1        0         0
14  15.0  167.708333      5      1        0         0
15  16.0  191.000000      5      1        0         0
16  17.0  194.375000      5      1        0         0
17  18.0  208.750000      5      1        0         0
18  19.0  167.416667      5      1        0         0
19  20.0  144.000000      5      1        0         0
20  21.0  186.833333      5      1        0         0
21  22.0  223.541667      5      1        0         0
22  23.0  219.782407      5      1        0         0
23  24.0  231.152778      5      1        0         0
24  25.0  248.958333      5      1        0         0
25  26.0  252.208333      5      1        0         0
26  27.0  229.708333      5      1        0         0
27  28.0  257.750000      5      1        0         0
28  29.0  225.541667      5      1        0         0
29  30.0  192.000000      5      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\2690312394.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\2690312394.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [191]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_jun25 = d_jun25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_jun25["Average"] = d_jun25.iloc[:, 1:].mean(axis=1)
#month number
d_jun25["Month"]=6
#one hot encoding
d_jun25["Delhi"]=1
d_jun25["Gwalior"]=0
d_jun25["Jabalpur"]=0
#dropping columns
d_jun_preprocess = d_jun25.drop(columns=d_jun25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_jun_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0  202.833333      6      1        0         0
1    2.0  156.875000      6      1        0         0
2    3.0  138.175926      6      1        0         0
3    4.0  178.750000      6      1        0         0
4    5.0  165.125000      6      1        0         0
5    6.0  148.875000      6      1        0         0
6    7.0  176.500000      6      1        0         0
7    8.0  186.944444      6      1        0         0
8    9.0  220.083333      6      1        0         0
9   10.0  218.541667      6      1        0         0
10  11.0  230.666667      6      1        0         0
11  12.0  193.166667      6      1        0         0
12  13.0  177.250000      6      1        0         0
13  14.0  156.166667      6      1        0         0
14  15.0  139.875000      6      1        0         0
15  16.0  111.250000      6      1        0         0
16  17.0  101.166667      6      1        0         0
17  18.0   82.541667      6      1        0         0
18  19.0   93.000000      6      1        0         0
19  20.0   78.500000      6      1        0         0
20  21.0   81.808642      6      1        0         0
21  22.0   85.791667      6      1        0         0
22  23.0  100.666667      6      1        0         0
23  24.0   99.000000      6      1        0         0
24  25.0  123.208333      6      1        0         0
25  26.0  108.805556      6      1        0         0
26  27.0   79.875000      6      1        0         0
27  28.0   87.541667      6      1        0         0
28  29.0   84.958333      6      1        0         0
29  30.0   73.791667      6      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3335555951.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3335555951.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [192]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_jul25 = d_jul25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_jul25["Average"] = d_jul25.iloc[:, 1:].mean(axis=1)
#month number
d_jul25["Month"]=7
#one hot encoding
d_jul25["Delhi"]=1
d_jul25["Gwalior"]=0
d_jul25["Jabalpur"]=0
#dropping columns
d_jul_preprocess = d_jul25.drop(columns=d_jul25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_jul_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0   83.277778      7      1        0         0
1    2.0   82.166667      7      1        0         0
2    3.0   73.875000      7      1        0         0
3    4.0   76.666667      7      1        0         0
4    5.0   86.000000      7      1        0         0
5    6.0   81.750000      7      1        0         0
6    7.0   81.833333      7      1        0         0
7    8.0   86.375000      7      1        0         0
8    9.0   85.291667      7      1        0         0
9   10.0   62.000000      7      1        0         0
10  11.0   75.666667      7      1        0         0
11  12.0   92.416667      7      1        0         0
12  13.0   82.208333      7      1        0         0
13  14.0   63.333333      7      1        0         0
14  15.0   50.083333      7      1        0         0
15  16.0   62.250000      7      1        0         0
16  17.0   71.708333      7      1        0         0
17  18.0   61.708333      7      1        0         0
18  19.0   57.166667      7      1        0         0
19  20.0   70.166667      7      1        0         0
20  21.0   84.083333      7      1        0         0
21  22.0   95.541667      7      1        0         0
22  23.0   71.888889      7      1        0         0
23  24.0   84.375000      7      1        0         0
24  25.0  127.708333      7      1        0         0
25  26.0   93.458333      7      1        0         0
26  27.0   86.416667      7      1        0         0
27  28.0   78.625000      7      1        0         0
28  29.0   79.916667      7      1        0         0
29  30.0   63.875000      7      1        0         0
30  31.0   58.791667      7      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1230673770.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1230673770.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [193]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_aug25 = d_aug25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_aug25["Average"] = d_aug25.iloc[:, 1:].mean(axis=1)
#month number
d_aug25["Month"]=8
#one hot encoding
d_aug25["Delhi"]=1
d_aug25["Gwalior"]=0
d_aug25["Jabalpur"]=0
#dropping columns
d_aug_preprocess = d_aug25.drop(columns=d_aug25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_aug_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0   61.666667      8      1        0         0
1    2.0   76.250000      8      1        0         0
2    3.0   81.500000      8      1        0         0
3    4.0  111.541667      8      1        0         0
4    5.0   99.708333      8      1        0         0
5    6.0   95.916667      8      1        0         0
6    7.0  109.861111      8      1        0         0
7    8.0  115.833333      8      1        0         0
8    9.0   93.291667      8      1        0         0
9   10.0   74.083333      8      1        0         0
10  11.0   99.583333      8      1        0         0
11  12.0  100.666667      8      1        0         0
12  13.0  112.666667      8      1        0         0
13  14.0  103.375000      8      1        0         0
14  15.0   74.666667      8      1        0         0
15  16.0  104.083333      8      1        0         0
16  17.0   91.708333      8      1        0         0
17  18.0   78.250000      8      1        0         0
18  19.0   88.375000      8      1        0         0
19  20.0   82.916667      8      1        0         0
20  21.0   77.208333      8      1        0         0
21  22.0   98.375000      8      1        0         0
22  23.0   98.666667      8      1        0         0
23  24.0   67.513889      8      1        0         0
24  25.0   61.458333      8      1        0         0
25  26.0   56.125000      8      1        0         0
26  27.0   71.208333      8      1        0         0
27  28.0  111.708333      8      1        0         0
28  29.0  105.958333      8      1        0         0
29  30.0   76.166667      8      1        0         0
30  31.0   80.608696      8      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1710687541.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1710687541.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [194]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_sep25_ = d_sep25_.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_sep25_["Average"] = d_sep25_.iloc[:, 1:].mean(axis=1)
#month number
d_sep25_["Month"]=9
#one hot encoding
d_sep25_["Delhi"]=1
d_sep25_["Gwalior"]=0
d_sep25_["Jabalpur"]=0
#dropping columns
d_sep_preprocess = d_sep25_.drop(columns=d_sep25_.loc[:, "00:00:00":"23:00:00"].columns)


print(d_sep_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0   60.708333      9      1        0         0
1    2.0   51.791667      9      1        0         0
2    3.0   55.041667      9      1        0         0
3    4.0   58.138889      9      1        0         0
4    5.0   66.736111      9      1        0         0
5    6.0   72.166667      9      1        0         0
6    7.0   81.333333      9      1        0         0
7    8.0   80.875000      9      1        0         0
8    9.0  101.958333      9      1        0         0
9   10.0   82.875000      9      1        0         0
10  11.0   90.916667      9      1        0         0
11  12.0  106.791667      9      1        0         0
12  13.0  108.458333      9      1        0         0
13  14.0  104.277778      9      1        0         0
14  15.0  113.041667      9      1        0         0
15  16.0  118.583333      9      1        0         0
16  17.0  111.958333      9      1        0         0
17  18.0  113.083333      9      1        0         0
18  19.0  133.958333      9      1        0         0
19  20.0  131.625000      9      1        0         0
20  21.0  126.833333      9      1        0         0
21  22.0  134.541667      9      1        0         0
22  23.0  128.041667      9      1        0         0
23  24.0  123.041667      9      1        0         0
24  25.0  121.958333      9      1        0         0
25  26.0  117.430556      9      1        0         0
26  27.0  140.416667      9      1        0         0
27  28.0  146.375000      9      1        0         0
28  29.0  110.833333      9      1        0         0
29  30.0  112.708333      9      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3580174793.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\3580174793.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [195]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_oct25 = d_oct25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_oct25["Average"] = d_oct25.iloc[:, 1:].mean(axis=1)
#month number
d_oct25["Month"]=10
#one hot encoding
d_oct25["Delhi"]=1
d_oct25["Gwalior"]=0
d_oct25["Jabalpur"]=0
#dropping columns
d_oct_preprocess = d_oct25.drop(columns=d_oct25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_oct_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0   94.166667     10      1        0         0
1    2.0  114.291667     10      1        0         0
2    3.0   92.333333     10      1        0         0
3    4.0  124.041667     10      1        0         0
4    5.0  151.000000     10      1        0         0
5    6.0  115.958333     10      1        0         0
6    7.0   71.083333     10      1        0         0
7    8.0   69.750000     10      1        0         0
8    9.0   96.902778     10      1        0         0
9   10.0  148.916667     10      1        0         0
10  11.0  191.333333     10      1        0         0
11  12.0  167.347826     10      1        0         0
12  13.0  173.916667     10      1        0         0
13  14.0  200.416667     10      1        0         0
14  15.0  213.819444     10      1        0         0
15  16.0  238.208333     10      1        0         0
16  17.0  247.083333     10      1        0         0
17  18.0  259.625000     10      1        0         0
18  19.0  287.416667     10      1        0         0
19  20.0  336.541667     10      1        0         0
20  21.0  352.000000     10      1        0         0
21  22.0  347.277778     10      1        0         0
22  23.0  319.513889     10      1        0         0
23  24.0  281.750000     10      1        0         0
24  25.0  278.291667     10      1        0         0
25  26.0  311.833333     10      1        0         0
26  27.0  295.375000     10      1        0         0
27  28.0  300.597222     10      1        0         0
28  29.0  280.458333     10      1        0         0
29  30.0  353.041667     10      1        0         0
30  31.0  252.750000     10      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\2372734106.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\2372734106.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [196]:
def fill_with_prev_avg(row):
    for i in range(len(row)):
        if pd.isna(row[i]) and i >= 3:
            row[i] = row[i-3:i].mean()
    return row

# Apply row-wise
d_nov25 = d_nov25.apply(fill_with_prev_avg, axis=1)



# Create new column with row-wise average (excluding first column)
d_nov25["Average"] = d_nov25.iloc[:, 1:].mean(axis=1)
#month number
d_nov25["Month"]=11
#one hot encoding
d_nov25["Delhi"]=1
d_nov25["Gwalior"]=0
d_nov25["Jabalpur"]=0
#dropping columns
d_nov_preprocess = d_nov25.drop(columns=d_nov25.loc[:, "00:00:00":"23:00:00"].columns)


print(d_nov_preprocess)

    Date     Average  Month  Delhi  Gwalior  Jabalpur
0    1.0  273.166667     11      1        0         0
1    2.0  365.041667     11      1        0         0
2    3.0  314.208333     11      1        0         0
3    4.0  297.583333     11      1        0         0
4    5.0  219.791667     11      1        0         0
5    6.0  281.416667     11      1        0         0
6    7.0  315.875000     11      1        0         0
7    8.0  348.916667     11      1        0         0
8    9.0  378.375000     11      1        0         0
9   10.0  357.750000     11      1        0         0
10  11.0  419.958333     11      1        0         0
11  12.0  415.416667     11      1        0         0
12  13.0  407.958333     11      1        0         0
13  14.0  393.166667     11      1        0         0
14  15.0  384.958333     11      1        0         0
15  16.0  379.833333     11      1        0         0
16  17.0  354.708333     11      1        0         0
17  18.0  361.958333     11      1        0         0
18  19.0  391.500000     11      1        0         0
19  20.0  394.055556     11      1        0         0
20  21.0  368.083333     11      1        0         0
21  22.0  365.708333     11      1        0         0
22  23.0  385.541667     11      1        0         0
23  24.0  388.208333     11      1        0         0
24  25.0  357.750000     11      1        0         0
25  26.0  333.375000     11      1        0         0
26  27.0  363.130435     11      1        0         0
27  28.0  374.875000     11      1        0         0
28  29.0  320.958333     11      1        0         0
29  30.0  276.583333     11      1        0         0

C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1600899022.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[i]) and i >= 3:
C:\Users\abhia\AppData\Local\Temp\ipykernel_10800\1600899022.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  row[i] = row[i-3:i].mean()

In [197]:
df=pd.concat([d_jan_preprocess_,d_feb_preprocess,d_mar_preprocess,d_apr_preprocess,d_may_preprocess,d_jun_preprocess,d_jul_preprocess,d_aug_preprocess,d_sep_preprocess,d_oct_preprocess,d_nov_preprocess,d_dec_preprocess],axis=0,ignore_index=True)
df

     Date     Average  Month  Delhi  Gwalior  Jabalpur
0     1.0  326.625000      1      1        0         0
1     2.0  316.750000      1      1        0         0
2     3.0  358.375000      1      1        0         0
3     4.0  381.319444      1      1        0         0
4     5.0  356.625000      1      1        0         0
..    ...         ...    ...    ...      ...       ...
359  27.0  368.625000     12      1        0         0
360  28.0  393.000000     12      1        0         0
361  29.0  402.416667     12      1        0         0
362  30.0  385.375000     12      1        0         0
363  31.0  379.958333     12      1        0         0

[364 rows x 6 columns]

In [198]:
df=df.to_excel("delhi_combined.xlsx")

### Jabalpur

In [199]:
import pandas as pd

jan = pd.read_excel("jabalpur_January_2025.xlsx")
feb = pd.read_excel("jabalpur_February_2025.xlsx")
mar = pd.read_excel("jabalpur_March_2025.xlsx")
apr = pd.read_excel("jabalpur_April_2025.xlsx")
may = pd.read_excel("jabalpur_May_2025.xlsx")
jun = pd.read_excel("jabalpur_June_2025.xlsx")
jul = pd.read_excel("jabalpur_July_2025.xlsx")
aug = pd.read_excel("jabalpur_August_2025.xlsx")
sep = pd.read_excel("jabalpur_September_2025.xlsx")
octo = pd.read_excel("jabalpur_October_2025.xlsx")
nov = pd.read_excel("jabalpur_November_2025.xlsx")
dec = pd.read_excel("jabalpur_December_2025.xlsx")

In [200]:
df1 = pd.concat(
    [jan, feb, mar, apr, may, jun, jul, aug, sep, octo, nov, dec],
    axis=0,
    ignore_index=True
)

In [201]:
df1 = df1.rename(columns={
    "daily_avg_aqi": "Average",
    "month": "Month",
    "delhi": "Delhi",
    "gwalior": "Gwalior",
    "jabalpur": "Jabalpur"
})

In [202]:
df1

     Date    Average  Gwalior  Jabalpur  Delhi  Month
0       1  75.416667        1         0      0      1
1       2  85.333333        1         0      0      1
2       3  80.083333        1         0      0      1
3       4  96.527778        1         0      0      1
4       5  78.208333        1         0      0      1
..    ...        ...      ...       ...    ...    ...
360    27  74.000000        1         0      0     12
361    28  82.250000        1         0      0     12
362    29  93.666667        1         0      0     12
363    30  76.625000        1         0      0     12
364    31  73.000000        1         0      0     12

[365 rows x 6 columns]

In [203]:
df1['Gwalior'] = 0
df1['Jabalpur'] = 1

In [204]:
df1

     Date    Average  Gwalior  Jabalpur  Delhi  Month
0       1  75.416667        0         1      0      1
1       2  85.333333        0         1      0      1
2       3  80.083333        0         1      0      1
3       4  96.527778        0         1      0      1
4       5  78.208333        0         1      0      1
..    ...        ...      ...       ...    ...    ...
360    27  74.000000        0         1      0     12
361    28  82.250000        0         1      0     12
362    29  93.666667        0         1      0     12
363    30  76.625000        0         1      0     12
364    31  73.000000        0         1      0     12

[365 rows x 6 columns]

In [205]:
# df1.to_excel("jabalpur_combined.xlsx")

In [206]:
import pandas as pd

jan_g = pd.read_excel("gwalior_January_2025.xlsx")
feb_g = pd.read_excel("gwalior_February_2025.xlsx")
mar_g = pd.read_excel("gwalior_March_2025.xlsx")
apr_g = pd.read_excel("gwalior_April_2025.xlsx")
may_g = pd.read_excel("gwalior_May_2025.xlsx")
jun_g = pd.read_excel("gwalior_June_2025.xlsx")
jul_g = pd.read_excel("gwalior_July_2025.xlsx")
aug_g = pd.read_excel("gwalior_August_2025.xlsx")
sep_g = pd.read_excel("gwalior_September_2025.xlsx")
oct_g = pd.read_excel("gwalior_October_2025.xlsx")
nov_g = pd.read_excel("gwalior_November_2025.xlsx")
dec_g = pd.read_excel("gwalior_December_2025.xlsx")

In [207]:
df2 = pd.concat(
    [jan_g, feb_g, mar_g, apr_g, may_g, jun_g, jul_g, aug_g, sep_g, oct_g, nov_g, dec_g],
    axis=0,
    ignore_index=True
)

In [208]:
df2 = df2.rename(columns={
    "daily_avg_aqi": "Average",
    "month": "Month",
    "delhi": "Delhi",
    "gwalior": "Gwalior",
    "jabalpur": "Jabalpur"
})

In [209]:
# df2.to_excel("gwalior_combined.xlsx")

In [210]:
df2

     Date     Average  Gwalior  Jabalpur  Delhi  Month
0       1   93.125000        1         0      0      1
1       2  124.916667        1         0      0      1
2       3  165.875000        1         0      0      1
3       4  190.680556        1         0      0      1
4       5  139.625000        1         0      0      1
..    ...         ...      ...       ...    ...    ...
360    27  199.041667        1         0      0     12
361    28  242.958333        1         0      0     12
362    29  197.833333        1         0      0     12
363    30  197.291667        1         0      0     12
364    31  190.666667        1         0      0     12

[365 rows x 6 columns]

### Combined

In [211]:

delhi = pd.read_excel("delhi_combined.xlsx")
jabalpur= pd.read_excel("jabalpur_combined.xlsx")
gwalior= pd.read_excel("gwalior_combined.xlsx")

In [212]:
df3 = pd.concat(
    [delhi,jabalpur,gwalior],
    axis=0,
    ignore_index=True
)

In [213]:
df3

      Unnamed: 0  Date     Average  Month  Delhi  Gwalior  Jabalpur
0              0     1  326.625000      1      1        0         0
1              1     2  316.750000      1      1        0         0
2              2     3  358.375000      1      1        0         0
3              3     4  381.319444      1      1        0         0
4              4     5  356.625000      1      1        0         0
...          ...   ...         ...    ...    ...      ...       ...
1089         360    27  199.041667     12      0        1         0
1090         361    28  242.958333     12      0        1         0
1091         362    29  197.833333     12      0        1         0
1092         363    30  197.291667     12      0        1         0
1093         364    31  190.666667     12      0        1         0

[1094 rows x 7 columns]

In [214]:
df3 = df3.drop(columns=["Unnamed: 0"], errors='ignore')

## date to correct form

In [215]:
df3['Date'] = df3['Date'].astype(int)

In [216]:
df3['Date'] = pd.to_datetime(
    df3['Month'].astype(str) + '-' + df3['Date'].astype(str) + '-2025',
    format='%m-%d-%Y'
)

In [217]:
df3.head(50)

         Date     Average  Month  Delhi  Gwalior  Jabalpur
0  2025-01-01  326.625000      1      1        0         0
1  2025-01-02  316.750000      1      1        0         0
2  2025-01-03  358.375000      1      1        0         0
3  2025-01-04  381.319444      1      1        0         0
4  2025-01-05  356.625000      1      1        0         0
5  2025-01-06  325.125000      1      1        0         0
6  2025-01-07  304.125000      1      1        0         0
7  2025-01-08  306.791667      1      1        0         0
8  2025-01-09  331.541667      1      1        0         0
9  2025-01-10  400.833333      1      1        0         0
10 2025-01-11  341.458333      1      1        0         0
11 2025-01-12  281.291667      1      1        0         0
12 2025-01-13  263.875000      1      1        0         0
13 2025-01-14  263.166667      1      1        0         0
14 2025-01-15  361.416667      1      1        0         0
15 2025-01-16  328.833333      1      1        0         0
16 2025-01-17  290.708333      1      1        0         0
17 2025-01-18  255.708333      1      1        0         0
18 2025-01-19  342.250000      1      1        0         0
19 2025-01-20  331.875000      1      1        0         0
20 2025-01-21  287.416667      1      1        0         0
21 2025-01-22  261.500000      1      1        0         0
22 2025-01-23  256.916667      1      1        0         0
23 2025-01-24  204.916667      1      1        0         0
24 2025-01-25  183.500000      1      1        0         0
25 2025-01-26  201.083333      1      1        0         0
26 2025-01-27  254.041667      1      1        0         0
27 2025-01-28  269.416667      1      1        0         0
28 2025-01-29  340.458333      1      1        0         0
29 2025-01-30  371.930556      1      1        0         0
30 2025-01-31  351.291667      1      1        0         0
31 2025-02-01  353.291667      2      1        0         0
32 2025-02-02  333.958333      2      1        0         0
33 2025-02-03  291.458333      2      1        0         0
34 2025-02-04  262.708333      2      1        0         0
35 2025-02-05  290.333333      2      1        0         0
36 2025-02-06  214.583333      2      1        0         0
37 2025-02-07  165.250000      2      1        0         0
38 2025-02-08  149.458333      2      1        0         0
39 2025-02-09  208.166667      2      1        0         0
40 2025-02-10  263.583333      2      1        0         0
41 2025-02-11  284.208333      2      1        0         0
42 2025-02-12  236.083333      2      1        0         0
43 2025-02-13  136.666667      2      1        0         0
44 2025-02-14  130.625000      2      1        0         0
45 2025-02-15  168.666667      2      1        0         0
46 2025-02-16  271.083333      2      1        0         0
47 2025-02-17  242.375000      2      1        0         0
48 2025-02-18  211.000000      2      1        0         0
49 2025-02-19  180.833333      2      1        0         0

In [218]:
df3['day'] = df3['Date'].dt.day
df3['day_of_week'] = df3['Date'].dt.dayofweek

In [219]:
df3

           Date     Average  Month  Delhi  Gwalior  Jabalpur  day  day_of_week
0    2025-01-01  326.625000      1      1        0         0    1            2
1    2025-01-02  316.750000      1      1        0         0    2            3
2    2025-01-03  358.375000      1      1        0         0    3            4
3    2025-01-04  381.319444      1      1        0         0    4            5
4    2025-01-05  356.625000      1      1        0         0    5            6
...         ...         ...    ...    ...      ...       ...  ...          ...
1089 2025-12-27  199.041667     12      0        1         0   27            5
1090 2025-12-28  242.958333     12      0        1         0   28            6
1091 2025-12-29  197.833333     12      0        1         0   29            0
1092 2025-12-30  197.291667     12      0        1         0   30            1
1093 2025-12-31  190.666667     12      0        1         0   31            2

[1094 rows x 8 columns]

In [220]:
df3['city'] = np.select(
    [
        df3['Gwalior'] == 1,
        df3['Jabalpur'] == 1,
        df3['Delhi'] == 1
    ],
    ['Gwalior', 'Jabalpur', 'Delhi'],
    default='Unknown'   # ✅ FIX
)

In [221]:
df3

,Date,Average,Month,Delhi,Gwalior,Jabalpur,day,day_of_week,city
0,2025-01-01,326.625000,1,1,0,0,1,2,Delhi
1,2025-01-02,316.750000,1,1,0,0,2,3,Delhi
2,2025-01-03,358.375000,1,1,0,0,3,4,Delhi
3,2025-01-04,381.319444,1,1,0,0,4,5,Delhi
4,2025-01-05,356.625000,1,1,0,0,5,6,Delhi
...,...,...,...,...,...,...,...,...,...
1089,2025-12-27,199.041667,12,0,1,0,27,5,Gwalior
1090,2025-12-28,242.958333,12,0,1,0,28,6,Gwalior
1091,2025-12-29,197.833333,12,0,1,0,29,0,Gwalior
1092,2025-12-30,197.291667,12,0,1,0,30,1,Gwalior
1093,2025-12-31,190.666667,12,0,1,0,31,2,Gwalior

In [225]:
df3 = df3.sort_values(by=['city', 'Date'])

In [229]:
df3.tail()

,Date,Average,Month,Delhi,Gwalior,Jabalpur,day,day_of_week,city
724,2025-12-27,74.000000,12,0,0,1,27,5,Jabalpur
725,2025-12-28,82.250000,12,0,0,1,28,6,Jabalpur
726,2025-12-29,93.666667,12,0,0,1,29,0,Jabalpur
727,2025-12-30,76.625000,12,0,0,1,30,1,Jabalpur
728,2025-12-31,73.000000,12,0,0,1,31,2,Jabalpur

In [231]:
df3['AQI_t-1'] = df3.groupby('city')['Average'].shift(1)
df3['AQI_t-2'] = df3.groupby('city')['Average'].shift(2)
df3['AQI_t-3'] = df3.groupby('city')['Average'].shift(3)

In [232]:
df3

,Date,Average,Month,Delhi,Gwalior,Jabalpur,day,day_of_week,city,AQI_t-1,AQI_t-2,AQI_t-3
0,2025-01-01,326.625000,1,1,0,0,1,2,Delhi,NaN,NaN,NaN
1,2025-01-02,316.750000,1,1,0,0,2,3,Delhi,326.625000,NaN,NaN
2,2025-01-03,358.375000,1,1,0,0,3,4,Delhi,316.750000,326.625000,NaN
3,2025-01-04,381.319444,1,1,0,0,4,5,Delhi,358.375000,316.750000,326.625000
4,2025-01-05,356.625000,1,1,0,0,5,6,Delhi,381.319444,358.375000,316.750000
...,...,...,...,...,...,...,...,...,...,...,...,...
724,2025-12-27,74.000000,12,0,0,1,27,5,Jabalpur,77.208333,83.125000,85.416667
725,2025-12-28,82.250000,12,0,0,1,28,6,Jabalpur,74.000000,77.208333,83.125000
726,2025-12-29,93.666667,12,0,0,1,29,0,Jabalpur,82.250000,74.000000,77.208333
727,2025-12-30,76.625000,12,0,0,1,30,1,Jabalpur,93.666667,82.250000,74.000000
728,2025-12-31,73.000000,12,0,0,1,31,2,Jabalpur,76.625000,93.666667,82.250000

In [233]:
df3 = df3.dropna()

In [236]:
df3 = df3.rename(columns={'Average': 'AQI'})

In [237]:
df3

,Date,AQI,Month,Delhi,Gwalior,Jabalpur,day,day_of_week,city,AQI_t-1,AQI_t-2,AQI_t-3
3,2025-01-04,381.319444,1,1,0,0,4,5,Delhi,358.375000,316.750000,326.625000
4,2025-01-05,356.625000,1,1,0,0,5,6,Delhi,381.319444,358.375000,316.750000
5,2025-01-06,325.125000,1,1,0,0,6,0,Delhi,356.625000,381.319444,358.375000
6,2025-01-07,304.125000,1,1,0,0,7,1,Delhi,325.125000,356.625000,381.319444
7,2025-01-08,306.791667,1,1,0,0,8,2,Delhi,304.125000,325.125000,356.625000
...,...,...,...,...,...,...,...,...,...,...,...,...
724,2025-12-27,74.000000,12,0,0,1,27,5,Jabalpur,77.208333,83.125000,85.416667
725,2025-12-28,82.250000,12,0,0,1,28,6,Jabalpur,74.000000,77.208333,83.125000
726,2025-12-29,93.666667,12,0,0,1,29,0,Jabalpur,82.250000,74.000000,77.208333
727,2025-12-30,76.625000,12,0,0,1,30,1,Jabalpur,93.666667,82.250000,74.000000
728,2025-12-31,73.000000,12,0,0,1,31,2,Jabalpur,76.625000,93.666667,82.250000

In [238]:
city_mapping = {
    'Delhi': 1,
    'Gwalior': 2,
    'Jabalpur': 3
}

df3['city'] = df3['city'].map(city_mapping)

In [239]:
df3

,Date,AQI,Month,Delhi,Gwalior,Jabalpur,day,day_of_week,city,AQI_t-1,AQI_t-2,AQI_t-3
3,2025-01-04,381.319444,1,1,0,0,4,5,1,358.375000,316.750000,326.625000
4,2025-01-05,356.625000,1,1,0,0,5,6,1,381.319444,358.375000,316.750000
5,2025-01-06,325.125000,1,1,0,0,6,0,1,356.625000,381.319444,358.375000
6,2025-01-07,304.125000,1,1,0,0,7,1,1,325.125000,356.625000,381.319444
7,2025-01-08,306.791667,1,1,0,0,8,2,1,304.125000,325.125000,356.625000
...,...,...,...,...,...,...,...,...,...,...,...,...
724,2025-12-27,74.000000,12,0,0,1,27,5,3,77.208333,83.125000,85.416667
725,2025-12-28,82.250000,12,0,0,1,28,6,3,74.000000,77.208333,83.125000
726,2025-12-29,93.666667,12,0,0,1,29,0,3,82.250000,74.000000,77.208333
727,2025-12-30,76.625000,12,0,0,1,30,1,3,93.666667,82.250000,74.000000
728,2025-12-31,73.000000,12,0,0,1,31,2,3,76.625000,93.666667,82.250000